# Generated by Django 5.1.2 on 2025-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='b2_photos/')),
                ('comittee', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=125)),
            ],
        ),
    ]
