# Generated by Django 5.1.2 on 2024-12-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Intake',
        ),
    ]
