# Generated by Django 5.1.2 on 2025-10-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_course_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('venue', models.ManyToManyField(blank=True, related_name='venues', to='championship.championship')),
            ],
        ),
        migrations.CreateModel(
            name='Champie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('designation', models.CharField(choices=[('Student', 'Student'), ('Primary Teacher', 'Primary Teacher'), ('Secondary Teacher', 'Secondary Teacher'), ('Other', 'Other')], max_length=20)),
                ('photo', models.ImageField(upload_to='champie_photos/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.level')),
                ('championship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='championship.championship')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championship.cvenue')),
            ],
        ),
    ]
