# Generated by Django 5.1.2 on 2025-10-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_course_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='XCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='XTrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('photo', models.ImageField(upload_to='xtrainee_photos/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcom.xcourse')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.district')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcom.xvenue')),
            ],
        ),
        migrations.AddField(
            model_name='xcourse',
            name='venue',
            field=models.ManyToManyField(to='xcom.xvenue'),
        ),
    ]
