# Generated by Django 5.1.2 on 2025-01-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xtrainee',
            name='designation',
        ),
    ]
