# Generated by Django 5.1.2 on 2024-12-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_trainee_course_remove_level_course_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discipline',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='discipline',
            new_name='course',
        ),
    ]
